# Generated by Django 4.2.3 on 2023-07-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0002_alter_moodentry_mood_overall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughtprocessing',
            name='thought_distortion',
            field=models.CharField(max_length=100),
        ),
    ]
